services:
  ollama:
    image: ollama/ollama:0.1.44
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "11434"
    environment:
      - OLLAMA_NUM_PARALLEL=12
      - OLLAMA_MAX_LOADED_MODELS=2
    volumes:
      - ./.docker/data/ollama:/root/.ollama
    # Add support for GPU on the server.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
