services:
  model:
    image: ollama/ollama:0.1.38
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "11434"
    volumes:
      - ./.docker/data/ollama:/root/.ollama
