<?php

/**
 * @file
 * Modules default module file.
 */

/**
 * Implements hook_theme().
 */
function chat_theme(): array {
  return [
    'chat_block' => [
      'variables' => [
        'buttons' => FALSE,
        'provider_name' => '',
        'models' => [],
        'system_prompt' => '',
        'temperature' => 0.8,
        'top_k' => 40,
        'top_p' => 0.9,
        'context_expire' => 3600,
      ],
    ],
  ];
}
